---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@cae02393710f18f5fbacd9545d1a38f0d661758e # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
