---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@8f11430bdcbaacd3be7dc94a105915882f3c340b # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
