---
name: Add issues to project board

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/add-to-project@09285e01c1fe597f667fc839e2d3a819c61e4716 # v0
        with:
          project-token: ${{ secrets.PROJECT_PAT }}
