name: deploy

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/chktex@v0.10.0

  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/vale@v0.10.0

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/compile@v0.10.0

      - name: Upload artefacts
        uses: actions/upload-artifact@v3
        with:
          name: artefacts
          path: "*.pdf"
          if-no-files-found: error

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v3
        with:
          name: artefacts

      - uses: paddyroddy/.github/actions/dropbox@v0.10.0
        with:
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
