---
name: Deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/chktex@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0

  vale:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/vale@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  compile-latex:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/compile@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0

      - name: Upload artefacts
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: artefacts
          path: "*.pdf"
          if-no-files-found: error

  upload-to-dropbox:
    if: github.ref == 'refs/heads/main'
    needs: compile-latex
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      - name: Download artefacts
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: artefacts

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/dropbox@dca9a13d483fe335f0b9edbd08494e6e4cd3b498 # v0
        with:
          # yamllint disable rule:line-length
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }} # zizmor: ignore[secrets-outside-env]
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }} # zizmor: ignore[secrets-outside-env]
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }} # zizmor: ignore[secrets-outside-env]
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }} # zizmor: ignore[secrets-outside-env]
          # yamllint enable rule:line-length
