name: deploy

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/chktex@34e390ddee5772749fb85130dc096071b690a7b7 # v0

  vale:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/vale@34e390ddee5772749fb85130dc096071b690a7b7 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/latex/compile@34e390ddee5772749fb85130dc096071b690a7b7 # v0

      - name: Upload artefacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: artefacts
          path: "*.pdf"
          if-no-files-found: error

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: artefacts

      - uses: paddyroddy/.github/actions/dropbox@34e390ddee5772749fb85130dc096071b690a7b7 # v0
        with:
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }}
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }}
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
