---
name: deploy

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/chktex@6945dc7543c02201ffb88ace2286439798acbda8 # v0

  vale:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/vale@6945dc7543c02201ffb88ace2286439798acbda8 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/compile@6945dc7543c02201ffb88ace2286439798acbda8 # v0

      - name: Upload artefacts
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: artefacts
          path: "*.pdf"
          if-no-files-found: error

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@87c55149d96e628cc2ef7e6fc2aab372015aec85 # v4
        with:
          name: artefacts

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/dropbox@v0
        with:
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }}
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }}
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
