---
name: deploy

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  chktex:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/chktex@1a3be93a5bbb79658efc285ce792da79745d9d32 # v0

  vale:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/vale@1a3be93a5bbb79658efc285ce792da79745d9d32 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  compile-latex:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/latex/compile@1a3be93a5bbb79658efc285ce792da79745d9d32 # v0

      - name: Upload artefacts
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: artefacts
          path: "*.pdf"
          if-no-files-found: error

  upload-to-dropbox:
    runs-on: ubuntu-latest
    needs: compile-latex
    steps:
      - name: Download artefacts
        # yamllint disable-line rule:line-length
        uses: actions/download-artifact@f44cd7b40bfd40b6aa1cc1b9b5b7bf03d3c67110 # v4
        with:
          name: artefacts

      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/dropbox@1a3be93a5bbb79658efc285ce792da79745d9d32 # v0
        with:
          configfile-version: ${{ secrets.CONFIGFILE_VERSION }}
          files-to-upload: $(find . -maxdepth 1 -name '*.pdf' -print)
          oauth-app-key: ${{ secrets.OAUTH_APP_KEY }}
          oauth-app-secret: ${{ secrets.OAUTH_APP_SECRET }}
          oauth-refresh-token: ${{ secrets.OAUTH_REFRESH_TOKEN }}
