name: Update Copyright

on:
  schedule:
    - cron: "0 3 1 1 *"

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      - uses: paddyroddy/.github/actions/licence@2875a6d0e8cde7569a844579e5528338cffae08f # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          licence-file: ./LICENCE.md
