name: Update Copyright

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 3 1 1 *"

jobs:
  update-licence-year:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@ed26e5e29e6e6f95c4298be97823398fdf3fc6bf # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          licence-file: ./LICENCE.md
