---
name: Update Copyright

on:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  update-licence-year:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/licence@d8b5e17744d755a47bf422892762841f313f3dfe # v0
        env:
          LICENCE_TOKEN: ${{ secrets.LICENCE_PAT }}
        with:
          licence-file: ./LICENCE.txt
          licence-token: ${{ env.LICENCE_TOKEN }}
