---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@09285e01c1fe597f667fc839e2d3a819c61e4716 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
