---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@92f5b02366f48f287deea60661b0bdb1cec1a427 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
