---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@d8b5e17744d755a47bf422892762841f313f3dfe # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
