---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    permissions:
      contents: read
    runs-on: ubuntu-slim
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@d8b5e17744d755a47bf422892762841f313f3dfe # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
