---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@8f11430bdcbaacd3be7dc94a105915882f3c340b # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
